/*
  AUTO-GENERATED by scripts/import-clinccalc-top300.ts
  DO NOT EDIT MANUALLY.
*/

export type IPNTop300DrugSeed = {
  rank: number;
  canonicalGenericName: string;
  aliases: string[];
  therapeuticClasses: string[];
  dispensedDosageForms: string[];
  firstDosageForm?: string;
};

export const IPN_TOP300_DRUGS: IPNTop300DrugSeed[] = [
  {
    "rank": 1,
    "canonicalGenericName": "Atorvastatin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 2,
    "canonicalGenericName": "Metformin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 3,
    "canonicalGenericName": "Levothyroxine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 4,
    "canonicalGenericName": "Lisinopril",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 5,
    "canonicalGenericName": "Amlodipine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 6,
    "canonicalGenericName": "Metoprolol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 7,
    "canonicalGenericName": "Albuterol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 8,
    "canonicalGenericName": "Losartan",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 9,
    "canonicalGenericName": "Gabapentin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 10,
    "canonicalGenericName": "Omeprazole",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 11,
    "canonicalGenericName": "Sertraline",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 12,
    "canonicalGenericName": "Rosuvastatin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 13,
    "canonicalGenericName": "Pantoprazole",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 14,
    "canonicalGenericName": "Escitalopram",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 15,
    "canonicalGenericName": "Dextroamphetamine; Dextroamphetamine Saccharate; Amphetamine; Amphetamine Aspartate",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 16,
    "canonicalGenericName": "Hydrochlorothiazide",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 17,
    "canonicalGenericName": "Bupropion",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 18,
    "canonicalGenericName": "Fluoxetine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 19,
    "canonicalGenericName": "Semaglutide",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 20,
    "canonicalGenericName": "Montelukast",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 21,
    "canonicalGenericName": "Trazodone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 22,
    "canonicalGenericName": "Simvastatin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 23,
    "canonicalGenericName": "Amoxicillin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 24,
    "canonicalGenericName": "Tamsulosin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 25,
    "canonicalGenericName": "Acetaminophen; Hydrocodone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 26,
    "canonicalGenericName": "Fluticasone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 27,
    "canonicalGenericName": "Meloxicam",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 28,
    "canonicalGenericName": "Apixaban",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 29,
    "canonicalGenericName": "Furosemide",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 30,
    "canonicalGenericName": "Insulin Glargine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 31,
    "canonicalGenericName": "Duloxetine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 32,
    "canonicalGenericName": "Ibuprofen",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 33,
    "canonicalGenericName": "Famotidine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 34,
    "canonicalGenericName": "Empagliflozin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 35,
    "canonicalGenericName": "Carvedilol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 36,
    "canonicalGenericName": "Tramadol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 37,
    "canonicalGenericName": "Alprazolam",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 38,
    "canonicalGenericName": "Prednisone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 39,
    "canonicalGenericName": "Hydroxyzine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 40,
    "canonicalGenericName": "Buspirone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 41,
    "canonicalGenericName": "Clopidogrel",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 42,
    "canonicalGenericName": "Glipizide",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 43,
    "canonicalGenericName": "Citalopram",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 44,
    "canonicalGenericName": "Potassium Chloride",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 45,
    "canonicalGenericName": "Allopurinol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 46,
    "canonicalGenericName": "Aspirin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 47,
    "canonicalGenericName": "Cyclobenzaprine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 48,
    "canonicalGenericName": "Ergocalciferol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 49,
    "canonicalGenericName": "Oxycodone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 50,
    "canonicalGenericName": "Methylphenidate",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 51,
    "canonicalGenericName": "Venlafaxine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 52,
    "canonicalGenericName": "Spironolactone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 53,
    "canonicalGenericName": "Ondansetron",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 54,
    "canonicalGenericName": "Zolpidem",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 55,
    "canonicalGenericName": "Cetirizine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 56,
    "canonicalGenericName": "Estradiol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 57,
    "canonicalGenericName": "Pravastatin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 58,
    "canonicalGenericName": "Hydrochlorothiazide; Lisinopril",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 59,
    "canonicalGenericName": "Lamotrigine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 60,
    "canonicalGenericName": "Quetiapine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 61,
    "canonicalGenericName": "Fluticasone; Salmeterol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 62,
    "canonicalGenericName": "Clonazepam",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 63,
    "canonicalGenericName": "Dulaglutide",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 64,
    "canonicalGenericName": "Azithromycin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 65,
    "canonicalGenericName": "Hydrochlorothiazide; Losartan",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 66,
    "canonicalGenericName": "Amoxicillin; Clavulanate",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 67,
    "canonicalGenericName": "Latanoprost",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 68,
    "canonicalGenericName": "Cholecalciferol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 69,
    "canonicalGenericName": "Propranolol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 70,
    "canonicalGenericName": "Ezetimibe",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 71,
    "canonicalGenericName": "Topiramate",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 72,
    "canonicalGenericName": "Paroxetine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 73,
    "canonicalGenericName": "Diclofenac",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 74,
    "canonicalGenericName": "Budesonide; Formoterol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 75,
    "canonicalGenericName": "Atenolol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 76,
    "canonicalGenericName": "Lisdexamfetamine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 77,
    "canonicalGenericName": "Doxycycline",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 78,
    "canonicalGenericName": "Pregabalin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 79,
    "canonicalGenericName": "Ethinyl Estradiol; Norethindrone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 80,
    "canonicalGenericName": "Glimepiride",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 81,
    "canonicalGenericName": "Tizanidine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 82,
    "canonicalGenericName": "Clonidine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 83,
    "canonicalGenericName": "Fenofibrate",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 84,
    "canonicalGenericName": "Insulin Lispro",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 85,
    "canonicalGenericName": "Valsartan",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 86,
    "canonicalGenericName": "Cephalexin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 87,
    "canonicalGenericName": "Baclofen",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 88,
    "canonicalGenericName": "Rivaroxaban",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 89,
    "canonicalGenericName": "Ferrous Sulfate",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 90,
    "canonicalGenericName": "Amitriptyline",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 91,
    "canonicalGenericName": "Finasteride",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 92,
    "canonicalGenericName": "Dapagliflozin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 93,
    "canonicalGenericName": "Acetaminophen; Oxycodone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 94,
    "canonicalGenericName": "Folic Acid",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 95,
    "canonicalGenericName": "Aripiprazole",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 96,
    "canonicalGenericName": "Olmesartan",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 97,
    "canonicalGenericName": "Ethinyl Estradiol; Norgestimate",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 98,
    "canonicalGenericName": "Valacyclovir",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 99,
    "canonicalGenericName": "Mirtazapine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 100,
    "canonicalGenericName": "Lorazepam",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 101,
    "canonicalGenericName": "Levetiracetam",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 102,
    "canonicalGenericName": "Insulin Aspart",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 103,
    "canonicalGenericName": "Naproxen",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 104,
    "canonicalGenericName": "Cyanocobalamin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 105,
    "canonicalGenericName": "Loratadine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 106,
    "canonicalGenericName": "Diltiazem",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 107,
    "canonicalGenericName": "Sumatriptan",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 108,
    "canonicalGenericName": "Triamcinolone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 109,
    "canonicalGenericName": "Hydralazine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 110,
    "canonicalGenericName": "Tirzepatide",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 111,
    "canonicalGenericName": "Celecoxib",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 112,
    "canonicalGenericName": "Acetaminophen",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 113,
    "canonicalGenericName": "Alendronate",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 114,
    "canonicalGenericName": "Oxybutynin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 115,
    "canonicalGenericName": "Hydrochlorothiazide; Triamterene",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 116,
    "canonicalGenericName": "Warfarin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 117,
    "canonicalGenericName": "Progesterone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 118,
    "canonicalGenericName": "Fluticasone; Umeclidinium; Vilanterol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 119,
    "canonicalGenericName": "Testosterone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 120,
    "canonicalGenericName": "Nifedipine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 121,
    "canonicalGenericName": "Methocarbamol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 122,
    "canonicalGenericName": "Benzonatate",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 123,
    "canonicalGenericName": "Sitagliptin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 124,
    "canonicalGenericName": "Chlorthalidone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 125,
    "canonicalGenericName": "Isosorbide",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 126,
    "canonicalGenericName": "Donepezil",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 127,
    "canonicalGenericName": "Dexmethylphenidate",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 128,
    "canonicalGenericName": "Sulfamethoxazole; Trimethoprim",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 129,
    "canonicalGenericName": "Clobetasol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 130,
    "canonicalGenericName": "Methotrexate",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 131,
    "canonicalGenericName": "Hydroxychloroquine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 132,
    "canonicalGenericName": "Lovastatin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 133,
    "canonicalGenericName": "Pioglitazone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 134,
    "canonicalGenericName": "Irbesartan",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 135,
    "canonicalGenericName": "Methylprednisolone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 136,
    "canonicalGenericName": "Norethindrone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 137,
    "canonicalGenericName": "Meclizine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 138,
    "canonicalGenericName": "Ethinyl Estradiol; Levonorgestrel",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 139,
    "canonicalGenericName": "Fluticasone; Vilanterol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 140,
    "canonicalGenericName": "Ketoconazole",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 141,
    "canonicalGenericName": "Thyroid",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 142,
    "canonicalGenericName": "Azelastine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 143,
    "canonicalGenericName": "Nitrofurantoin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 144,
    "canonicalGenericName": "Adalimumab",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 145,
    "canonicalGenericName": "Memantine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 146,
    "canonicalGenericName": "Prednisolone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 147,
    "canonicalGenericName": "Esomeprazole",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 148,
    "canonicalGenericName": "Docusate",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 149,
    "canonicalGenericName": "Clindamycin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 150,
    "canonicalGenericName": "Acyclovir",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 151,
    "canonicalGenericName": "Sildenafil",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 152,
    "canonicalGenericName": "Insulin Degludec",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 153,
    "canonicalGenericName": "Insulin Detemir",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 154,
    "canonicalGenericName": "Drospirenone; Ethinyl Estradiol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 155,
    "canonicalGenericName": "Ciprofloxacin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 156,
    "canonicalGenericName": "Morphine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 157,
    "canonicalGenericName": "Insulin Human; Insulin Isophane Human",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 158,
    "canonicalGenericName": "Levocetirizine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 159,
    "canonicalGenericName": "Nirmatrelvir; Ritonavir",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 160,
    "canonicalGenericName": "Valproate",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 161,
    "canonicalGenericName": "Atomoxetine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 162,
    "canonicalGenericName": "Budesonide",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 163,
    "canonicalGenericName": "Tiotropium",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 164,
    "canonicalGenericName": "Melatonin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 165,
    "canonicalGenericName": "Cefdinir",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 166,
    "canonicalGenericName": "Doxepin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 167,
    "canonicalGenericName": "Olanzapine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 168,
    "canonicalGenericName": "Phentermine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 169,
    "canonicalGenericName": "Ofloxacin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 170,
    "canonicalGenericName": "Ethinyl Estradiol; Etonogestrel",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 171,
    "canonicalGenericName": "Mupirocin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 172,
    "canonicalGenericName": "Benazepril",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 173,
    "canonicalGenericName": "Timolol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 174,
    "canonicalGenericName": "Magnesium Salts",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 175,
    "canonicalGenericName": "Fluconazole",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 176,
    "canonicalGenericName": "Risperidone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 177,
    "canonicalGenericName": "Verapamil",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 178,
    "canonicalGenericName": "Linaclotide",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 179,
    "canonicalGenericName": "Cyclosporine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 180,
    "canonicalGenericName": "Doxazosin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 181,
    "canonicalGenericName": "Albuterol; Ipratropium",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 182,
    "canonicalGenericName": "Hydrocortisone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 183,
    "canonicalGenericName": "Diazepam",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 184,
    "canonicalGenericName": "Telmisartan",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 185,
    "canonicalGenericName": "Carbamazepine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 186,
    "canonicalGenericName": "Amlodipine; Benazepril",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 187,
    "canonicalGenericName": "Lithium",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 188,
    "canonicalGenericName": "Evolocumab",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 189,
    "canonicalGenericName": "Desvenlafaxine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 190,
    "canonicalGenericName": "Dorzolamide",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 191,
    "canonicalGenericName": "Nebivolol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 192,
    "canonicalGenericName": "Dicyclomine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 193,
    "canonicalGenericName": "Torsemide",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 194,
    "canonicalGenericName": "Anastrozole",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 195,
    "canonicalGenericName": "Enalapril",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 196,
    "canonicalGenericName": "Polyethylene Glycol 3350",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 197,
    "canonicalGenericName": "Tretinoin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 198,
    "canonicalGenericName": "Tadalafil",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 199,
    "canonicalGenericName": "Sacubitril; Valsartan",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 200,
    "canonicalGenericName": "Calcium",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 201,
    "canonicalGenericName": "Pramipexole",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 202,
    "canonicalGenericName": "Mesalamine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 203,
    "canonicalGenericName": "Metronidazole",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 204,
    "canonicalGenericName": "Nortriptyline",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 205,
    "canonicalGenericName": "Emtricitabine; Tenofovir",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 206,
    "canonicalGenericName": "Rimegepant",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 207,
    "canonicalGenericName": "Nitroglycerin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 208,
    "canonicalGenericName": "Rizatriptan",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 209,
    "canonicalGenericName": "Liraglutide",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 210,
    "canonicalGenericName": "Acetaminophen; Codeine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 211,
    "canonicalGenericName": "Ramipril",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 212,
    "canonicalGenericName": "Ropinirole",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 213,
    "canonicalGenericName": "Brimonidine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 214,
    "canonicalGenericName": "Mirabegron",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 215,
    "canonicalGenericName": "Colchicine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 216,
    "canonicalGenericName": "Ticagrelor",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 217,
    "canonicalGenericName": "Terazosin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 218,
    "canonicalGenericName": "Amiodarone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 219,
    "canonicalGenericName": "Fexofenadine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 220,
    "canonicalGenericName": "Liothyronine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 221,
    "canonicalGenericName": "Bisoprolol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 222,
    "canonicalGenericName": "Omega-3-acid Ethyl Esters",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 223,
    "canonicalGenericName": "Flecainide",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 224,
    "canonicalGenericName": "Oxcarbazepine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 225,
    "canonicalGenericName": "Desogestrel; Ethinyl Estradiol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 226,
    "canonicalGenericName": "Ascorbic Acid",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 227,
    "canonicalGenericName": "Sodium Salts",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 228,
    "canonicalGenericName": "Ketorolac",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 229,
    "canonicalGenericName": "Dorzolamide; Timolol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 230,
    "canonicalGenericName": "Promethazine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 231,
    "canonicalGenericName": "Levofloxacin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 232,
    "canonicalGenericName": "Labetalol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 233,
    "canonicalGenericName": "Nystatin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 234,
    "canonicalGenericName": "Cyproheptadine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 235,
    "canonicalGenericName": "Erythromycin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 236,
    "canonicalGenericName": "Dutasteride",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 237,
    "canonicalGenericName": "Moxifloxacin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 238,
    "canonicalGenericName": "Bimatoprost",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 239,
    "canonicalGenericName": "Primidone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 240,
    "canonicalGenericName": "Sucralfate",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 241,
    "canonicalGenericName": "Betamethasone; Clotrimazole",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 242,
    "canonicalGenericName": "Senna; Docusate",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 243,
    "canonicalGenericName": "Bumetanide",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 244,
    "canonicalGenericName": "Icosapent Ethyl",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 245,
    "canonicalGenericName": "Solifenacin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 246,
    "canonicalGenericName": "Dexamethasone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 247,
    "canonicalGenericName": "Epinephrine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 248,
    "canonicalGenericName": "Penicillin V",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 249,
    "canonicalGenericName": "Calcitriol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 250,
    "canonicalGenericName": "Oseltamivir",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 251,
    "canonicalGenericName": "Polymyxin B; Trimethoprim",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 252,
    "canonicalGenericName": "Dextromethorphan; Promethazine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 253,
    "canonicalGenericName": "Terbinafine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 254,
    "canonicalGenericName": "Linagliptin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 255,
    "canonicalGenericName": "Methimazole",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 256,
    "canonicalGenericName": "Metoclopramide",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 257,
    "canonicalGenericName": "Medroxyprogesterone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 258,
    "canonicalGenericName": "Pancrelipase Amylase; Pancrelipase Lipase; Pancrelipase Protease",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 259,
    "canonicalGenericName": "Clotrimazole",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 260,
    "canonicalGenericName": "Dexamethasone; Neomycin; Polymyxin B",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 261,
    "canonicalGenericName": "Calcium Phosphate; Cholecalciferol",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 262,
    "canonicalGenericName": "Acetaminophen; Butalbital; Caffeine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 263,
    "canonicalGenericName": "Guanfacine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 264,
    "canonicalGenericName": "Sodium Fluoride",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 265,
    "canonicalGenericName": "Codeine; Guaifenesin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 266,
    "canonicalGenericName": "Lactulose",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 267,
    "canonicalGenericName": "Fluorouracil",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 268,
    "canonicalGenericName": "Ipratropium",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 269,
    "canonicalGenericName": "Olopatadine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 270,
    "canonicalGenericName": "Chlorhexidine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 271,
    "canonicalGenericName": "Nabumetone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 272,
    "canonicalGenericName": "Mometasone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 273,
    "canonicalGenericName": "Polyethylene Glycol 3350 With Electrolytes",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 274,
    "canonicalGenericName": "Hydroquinone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 275,
    "canonicalGenericName": "Phenazopyridine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 276,
    "canonicalGenericName": "Loperamide",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 277,
    "canonicalGenericName": "Lidocaine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 278,
    "canonicalGenericName": "Ciclopirox",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 279,
    "canonicalGenericName": "Cefuroxime",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 280,
    "canonicalGenericName": "Betamethasone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 281,
    "canonicalGenericName": "Brompheniramine; Dextromethorphan; Pseudoephedrine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 282,
    "canonicalGenericName": "Ethinyl Estradiol; Norgestrel",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 283,
    "canonicalGenericName": "Ciprofloxacin; Dexamethasone",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 284,
    "canonicalGenericName": "Diphenhydramine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 285,
    "canonicalGenericName": "Ethinyl Estradiol; Norelgestromin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 286,
    "canonicalGenericName": "Atropine; Diphenoxylate",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 287,
    "canonicalGenericName": "Indomethacin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 288,
    "canonicalGenericName": "Niacin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 289,
    "canonicalGenericName": "Lactate",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 290,
    "canonicalGenericName": "Vitamin E",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 291,
    "canonicalGenericName": "Guaifenesin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 292,
    "canonicalGenericName": "Pseudoephedrine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 293,
    "canonicalGenericName": "Bisacodyl",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 294,
    "canonicalGenericName": "Riboflavin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 295,
    "canonicalGenericName": "Ivermectin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 296,
    "canonicalGenericName": "Etodolac",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 297,
    "canonicalGenericName": "Lactobacillus Acidophilus",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 298,
    "canonicalGenericName": "Tobramycin",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 299,
    "canonicalGenericName": "Ketotifen",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  },
  {
    "rank": 300,
    "canonicalGenericName": "Loratadine; Pseudoephedrine",
    "aliases": [],
    "therapeuticClasses": [],
    "dispensedDosageForms": []
  }
] as const;
