import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "../../lib/ipn-db";
import { PublicPage } from "../../lib/public-page";

export default async function ClaimFormPage({ params }: { params: Promise<{ npi: string }> }) {
  const { npi } = await params;
  const pharmacy = await db.pharmacy.findUnique({ where: { npi } });
  if (!pharmacy) notFound();
  return <PublicPage><div className="mx-auto max-w-2xl px-6 py-14"><h1 className="text-4xl font-black text-slate-950">Request profile claim</h1><p className="mt-3 text-slate-600">Submit your information and we’ll verify that you represent {pharmacy.name}.</p><form method="post" action="/api/claim-submissions" className="mt-8 grid gap-5 rounded-2xl border border-slate-200 p-6 shadow-sm"><input type="hidden" name="npi" value={npi} /><input type="hidden" name="pharmacyName" value={pharmacy.name} /><ReadOnly label="Pharmacy name" value={pharmacy.name} /><ReadOnly label="NPI" value={npi} /><div className="grid gap-5 sm:grid-cols-2"><Field label="Contact name" name="contactName" required /><Field label="Role / title" name="roleTitle" required /></div><Field label="Email" name="email" type="email" required /><Field label="Phone" name="phone" type="tel" required /><fieldset className="rounded-xl border border-amber-200 bg-amber-50 p-4"><legend className="px-2 font-bold text-slate-900">Assistance support (optional)</legend><label className="flex gap-3"><input type="checkbox" name="assistanceSupportEnabled" value="true" />Our pharmacy helps patients explore assistance options</label><div className="mt-4 grid gap-2 text-sm"><Check name="manufacturerAssistanceHelp" label="Manufacturer assistance" /><Check name="foundationAssistanceHelp" label="Foundation assistance" /><Check name="publicProgramHelp" label="Public programs" /><Check name="localAssistanceHelp" label="Local pharmacy assistance" /></div></fieldset><label className="font-semibold text-slate-800">Message (optional)<textarea name="message" rows={4} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 font-normal" /></label><button type="submit" className="rounded-xl bg-emerald-700 px-6 py-3 font-bold text-white">Request Profile Claim</button><Link href={`/pharmacy/${encodeURIComponent(npi)}`} className="font-semibold text-emerald-700">← Back to profile</Link></form></div></PublicPage>;
}
function Field({ label, name, type = "text", required = false }: { label: string; name: string; type?: string; required?: boolean }) { return <label className="font-semibold text-slate-800">{label}<input name={name} type={type} required={required} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 font-normal" /></label>; }
function ReadOnly({ label, value }: { label: string; value: string }) { return <div><p className="text-sm font-semibold text-slate-700">{label}</p><p className="mt-1 text-slate-950">{value}</p></div>; }
function Check({ name, label }: { name: string; label: string }) { return <label className="flex gap-3"><input type="checkbox" name={name} value="true" />{label}</label>; }
